add termux instruction
fyne-io/developer.fyne.io pull request #127
Opened 2023-05-05 10:45 UTC by MatejMagat305

2023-05-06 09:37 UTC, andydotxyz requested changes
I think you have duplicated the macOS section.
Also in this setup instructions we don't include code demos. 
I wonder if it should be included in the existing android tab?

2023-05-06 09:38 UTC, andydotxyz commented
One other thought is that this should not land until we have a release including the ability to build on termux.

2023-05-06 09:55 UTC, MatejMagat305 commented
ok, sorry, I will change it

2023-05-06 10:22 UTC, MatejMagat305 commented
> One other thought is that this should not land until we have a release including the ability to build on termux.

yes it us obvious (claer), it will wait until ....

2023-05-06 14:20 UTC, andydotxyz requested changes

2023-05-06 14:20 UTC, andydotxyz commented on started/index.md
> +        $ cd ~/fyne-termux && chmod 1777 fyne_install.sh
We should not instruct people to execute shell scripts from third party repositories to get started - this could represent a big security risk!

2023-05-06 14:21 UTC, andydotxyz commented
> Also in this setup instructions we don't include code demos.

This item was not addressed in the recent code changes - the setup tab is about platform specific install steps, not a code tutorial.

2023-05-06 14:30 UTC, MatejMagat305 commented
ok, I give up

2023-05-06 14:37 UTC, andydotxyz commented
> ok, I give up

Why? The instructions you added are really helpful - but we don't include demo code in the setup instructions...

2023-05-06 14:41 UTC, MatejMagat305 commented
ok, sorry, I have really stresfull day ..., so only write setup NDK and SDK on termux or how?

2023-05-06 14:42 UTC, andydotxyz commented
> ok, sorry, I have really stresfull day ..., so only write setup NDK and SDK on termux or how?

Yes, compare it to the other systems in that file. We include the operating-system specific steps required to get go/git/C installed and working. The "install Fyne" and "compile an app" all come after that block.

2023-06-03 20:22 UTC, andydotxyz requested changes
This content is all great - but I think the way the bullets flow it reads like development on android is the last step of developing on PC.

Can it be split into two separate sections?

2023-06-06 20:31 UTC, andydotxyz requested changes
Thanks for looking at this.
Remember this is just a getting set up guide.

As discussed before we don't want a full coding tutorial in this breakout box.
Isn't steps 1-4 all that is needed?

2023-06-08 12:23 UTC, andydotxyz approved these changes
Great thanks.

2023-06-08 12:24 UTC, merged