Add example to the tutorial for extending a widget's renderer
fyne-io/developer.fyne.io pull request #14
Opened 2020-11-26 22:32 UTC by justdan96

As title, I wasn't exactly sure how to phrase things so if anything needs editing please let me know!

2020-11-27 11:22 UTC, andydotxyz requested changes
This is a great addition, thanks.
A few comments about the wording and formatting but after a quick revision should be good to include.

2020-11-27 11:22 UTC, andydotxyz commented on tutorial/extending-widgets.md
> +	"image/color"
standard packages should go before fyne

2020-11-27 11:22 UTC, andydotxyz commented on tutorial/extending-widgets.md
> +	skinnedentry *skinnedEntry
I think recommended in Go would be `skinnedEntry` so the word break is clearer

2020-11-27 11:22 UTC, andydotxyz commented on tutorial/extending-widgets.md
> +We can also extend a widget and its renderer, allowing you to override its
The "and its" here does not seem needed - really we are only covering extending a renderer in this section

2020-11-27 11:22 UTC, andydotxyz commented on tutorial/extending-widgets.md
> +
To match the heading at the top, how about adding:

```
## Extending a Widget Renderer
```

or similar?
At some point we may rearrange the tutorials - this makes it clear it's a topic change

2020-11-27 11:22 UTC, andydotxyz commented on tutorial/extending-widgets.md
> +colour of the Entry widget, we first have to extend the Entry base widget
I'd remove "base" here - it could be confused with `BaseWidget`

2020-11-27 21:19 UTC, justdan96 commented
I've made the amendments suggested, let me know if you think it looks ready now.

2020-11-30 20:11 UTC, andydotxyz approved these changes
Great thanks

2020-12-01 18:05 UTC, merged