Reorganise and update content according to discussed plan
fyne-io/developer.fyne.io pull request #62
Opened 2021-12-22 01:17 UTC by andydotxyz

As the title says.
Rejigging content to have more at the top level nav. No more tour specific pages, just content.
Additionally tutorials are no longer separate - most went to "Extending Fyne" but not all.

Overall nav now is:
![devnav](https://user-images.githubusercontent.com/294436/147018350-2998c530-39f7-411b-96b8-45433f3e1f86.png)

2021-12-23 17:39 UTC, andydotxyz commented
I have managed to get it up and running temporarily for people without jekyll locally: http://18.134.241.169:4000/

2021-12-23 18:02 UTC, Jacalz requested changes
Here are some suggestions.

Exploring Fyne -> Widgets gets you a 404.

### Some other stuff while at it (suggestions):
I also think the testing tutorial needs to be updated now that the calculator isn't an example any more. FreeBSD arm64 also needs to be added to cross-compiling.

This was all of what I found. Looking really good.

2021-12-23 18:24 UTC, andydotxyz commented on started/packaging.md
> +// TODO merge this in
Thanks for catching this! document elements merged as I'd meant to do :)

2021-12-23 18:37 UTC, stuartmscott commented on index.md
> +        <p>If you can't wait to start coding your first Fyne app then you can dive right in at our developer documentation.</p>
I think the word 'coding' misleads the reader - if someone wanted to start coding, they would fire up an editor and start typing, not dive into documentation

2021-12-23 19:04 UTC, andydotxyz commented on index.md
> +        <p>If you can't wait to start coding your first Fyne app then you can dive right in at our developer documentation.</p>
Fixed

2021-12-24 09:03 UTC, Jacalz approved these changes
This looks good to me now. The sheer amount of changes makes it a bit hard to review but I have tried to look at everything to the best of my ability.

2021-12-24 17:12 UTC, merged