Update custom-theme.md with Workable example
fyne-io/developer.fyne.io pull request #79
Opened 2022-05-10 07:10 UTC by albertcausing

Workable Example for custom theme.

2022-05-10 15:43 UTC, Jacalz requested changes
Thanks for the example. I have a few suggestions for how it can be improved.

2022-05-10 15:43 UTC, Jacalz commented on extend/custom-theme.md
> +### Workable Example
I looked at the other tutorials and it seems to me like they don’t add a new section just for the code. We probably should stay consistent.
```suggestion
In the end, the resulting code could look something like this:
```

2022-05-10 15:43 UTC, Jacalz commented on extend/custom-theme.md
> +```
Let’s add some syntax highlighting to the code. It will be basically unreadable without.
```suggestion
```go
```

2022-05-15 21:22 UTC, andydotxyz commented
There is a lot of duplicated code - can we make the example a lot shorter as this is primarily documentation?

2022-06-02 05:53 UTC, Jacalz requested changes
I agree with Andy. We should ideally try to make the code example a bit shorter.

2024-01-27 22:49 UTC, andydotxyz commented
Feels pretty stale, please do consider bringing a shortened version to the docs.fyne.io repo.

2024-01-27 22:49 UTC, closed without merging